import os


DEFAULT_ADAPTER = os.getenv("DEFAULT_ADAPTER", "fortigate")
FORTIGATE_BASE_URL = os.getenv("FORTIGATE_BASE_URL", "https://fortigate.example.local")
FORTIGATE_TOKEN = os.getenv("FORTIGATE_TOKEN", "change-me")
FORTIGATE_VDOM = os.getenv("FORTIGATE_VDOM", "root")
FORTIGATE_QUARANTINE_GROUP = os.getenv("FORTIGATE_QUARANTINE_GROUP", "NON_COMPLIANT_ENDPOINTS")
PALOALTO_BASE_URL = os.getenv("PALOALTO_BASE_URL", "https://paloalto.example.local")
PALOALTO_TOKEN = os.getenv("PALOALTO_TOKEN", "change-me")
PALOALTO_SCOPE = os.getenv("PALOALTO_SCOPE", "shared")
PALOALTO_QUARANTINE_GROUP = os.getenv("PALOALTO_QUARANTINE_GROUP", "NON_COMPLIANT_ENDPOINTS")
PALOALTO_API_VERSION = os.getenv("PALOALTO_API_VERSION", "10.2")
PALOALTO_VERIFY_TLS = os.getenv("PALOALTO_VERIFY_TLS", "true").lower() == "true"
PALOALTO_PLACEHOLDER_IP = os.getenv("PALOALTO_PLACEHOLDER_IP", "203.0.113.254")
HTTP_TIMEOUT_SECONDS = float(os.getenv("HTTP_TIMEOUT_SECONDS", "10"))
HTTP_RETRIES = int(os.getenv("HTTP_RETRIES", "3"))
EVALUATION_ENGINE_URL = os.getenv("EVALUATION_ENGINE_URL", "http://127.0.0.1:8003")
INTER_SERVICE_API_KEY = os.getenv("POSTURE_API_KEY", "").strip()
FORTIGATE_VERIFY_TLS = os.getenv("FORTIGATE_VERIFY_TLS", "true").lower() == "true"
ASYNC_DECISION_EXECUTION = os.getenv("ASYNC_DECISION_EXECUTION", "false").lower() == "true"
BACKGROUND_WORKERS = int(os.getenv("BACKGROUND_WORKERS", "4"))
HTTP_CIRCUIT_BREAKER_THRESHOLD = int(os.getenv("HTTP_CIRCUIT_BREAKER_THRESHOLD", "5"))
HTTP_CIRCUIT_BREAKER_COOLDOWN_SECONDS = int(os.getenv("HTTP_CIRCUIT_BREAKER_COOLDOWN_SECONDS", "60"))
ALLOW_POLICY_HTTP_ACTIONS = os.getenv("ALLOW_POLICY_HTTP_ACTIONS", "true").lower() == "true"
ALLOW_PRIVATE_HTTP_TARGETS = os.getenv("ALLOW_PRIVATE_HTTP_TARGETS", "true").lower() == "true"
POLICY_HTTP_ALLOWED_HOSTS = {
    item.strip().lower()
    for item in os.getenv("POLICY_HTTP_ALLOWED_HOSTS", "").split(",")
    if item.strip()
}
ADAPTER_TOKEN_MASK = "********"
